spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: jungmo764@gmail.com
    password: ipyc bigm unib nzjb
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8
